### ISSUE TITLE
Alpha style label consistent with BibTeX alpha by default?

### ISSUE THREAD

**Issue by andrewdbate** [moewew/biblatex-trad#22]
Firstly, thanks for your efforts in developing this package!

When I use BibTeX alpha for a publication with many authors (e.g. Smith, Jones, Motik, Lehman, Lowe, Wang, Grau), the default label in BibTeX alpha looks like [SJML+96], but with trad-alpha I get [SJMLLWG96], which is too long.

Setting maxalphanames=4 in the usepackage options results in [Smi+96], which is not what I wanted either.

Any help would be appreciated.

(I am sorry if this is not a bug, but an error in my misunderstanding!)

**Comment by obama** [comment]
you should put that into the manual or something ;)

**Comment by moewew** [comment]
I have now settled with `maxalphanames=3, minalphanames=3` as well as `\renewcommand*{\labelalphaothers}{\textsuperscript{+}}` for `trad-alpha` (see the commits linked above). In my tests I only got three names and not four with `alpha.bst`.

Let me know what you think.

**Comment by moewew** [comment]
This should be fixed in version 0.3 which has been on CTAN for a bit now. Testing is, of course, still very much appreciated.
