### ISSUE TITLE
@phdthesis not output as expected

### ISSUE THREAD

**Issue by andrewdbate** [moewew/biblatex-trad#23]
Firstly, let me say thanks for the effort in developing this package -- I am using it for my PhD thesis.

However, the output I am getting when citing a phdthesis (at least when using trad-alpha) is different to what I was expecting (i.e. it is substantially different to BibTeX alpha).

For example, for the BibTeX entry

    @phdthesis{Tob01,
      author = {Stephan Tobies},
      title = {{Complexity Results and Practical Algorithms}},
      school = {LuFG Theoretical Computer Science, RWTH-Aachen},
      address = {Germany},
      year = 2001
    }

with the LaTeX document using BibTeX

    \documentclass{article}
    \begin{document}
    \cite{Tob01}
    \bibliographystyle{alpha}
    \bibliography{biblio}
    \end{document}

the reference is printed as

![bibtexalphacorrect](https://f.cloud.github.com/assets/2998569/1234004/64f98a5c-2952-11e3-95ef-fc9572090686.png)

whereas with the LaTeX document using BibLaTeX and trad-alpha

    \documentclass{article}
    \usepackage[backend=biber,style=trad-alpha]{biblatex}
    \addbibresource{biblio.bib}
    \begin{document}
    \cite{Tob01}
    \printbibliography
    \end{document}

this is the (incorrect output) that I am getting:

![biblatexalphaincorrect](https://f.cloud.github.com/assets/2998569/1234003/64e55b68-2952-11e3-995c-2448263326da.png)

**Comment by moewew** [comment]
If you are still interested in this, please pull the newest version from master and tell me what you think.

**Comment by russella** [comment]
I tested this (using the OPs bibtex entry), and it works perfectly. Would it be helpful if I added this to the testing file and generated a pull request?

**Comment by moewew** [comment]
Thanks for the feedback.

Extending the test files is never a bad idea, so please go ahead. If you happen to have other (real-world) examples (of other types) at hand don't hesitate to include those as well.

**Comment by moewew** [comment]
This should be fixed in version 0.3 which has been on CTAN for a bit now. Testing is, of course, still very much appreciated.

**Comment by andrewdbate** [comment]
Thank you for fixing this -- just in time for me writing up the thesis!

However, when I do an update with MiKTeX I don't see the new package... Am I doing something wrong? (I haven't had this before and Googling hasn't come up with much.)

Do I really need to download the package from the CTAN website and install it manually?

**Comment by moewew** [comment]
Mhhh, no indeed it seems as though the package has not been updated in MikTeX. The packages for MikTeX are maintained manually by the MikTeX developer.

You can download the files from CTAN (extract them) and replace the existing files on your system. (Normally it is not advised to do that, but since you are essentially doing an update that should be fine.)
