### ISSUE TITLE
Disable lowercasing?

### ISSUE THREAD

**Issue by larseggert** [moewew/biblatex-trad#27]
Is it possible to disable lowercasing of titles somehow?

**Comment by moewew** [comment]
I didn't check, but I suppose
```
\renewrobustcmd{\MakeTitleCase}[1]{#1}
```
or
```
\DeclareFieldFormat{titlecase}{#1}
```
could both do the trick.

**Comment by moewew** [comment]
Just so this has a more decisive answer. My preferred version would be
```latex
\DeclareFieldFormat{titlecase}{#1}
```
That field is used by the standard styles as well and so this approach is portable.
