### ISSUE TITLE
In biblatex 3.3. the format of \DeclareNameFormat has changed

### ISSUE THREAD

**Issue by kmindi** [moewew/biblatex-trad#30]
Illegal parameter number in definition of \blx@defformat@d. \usebibmacro{name:first-last}{#1}{#4

> In biblatex 3.3. the format of \DeclareNameFormat has changed. In its code part it no longer accepts 8 arguments, but only one. For the various parts of a name there are now macros which you get by splitting the main name data with \namepart.

 https://tex.stackexchange.com/questions/299036/biblatex-3-3-name-formatting

**Comment by moewew** [comment]
See also #25
