### ISSUE TITLE
@incollection not output as expected

### ISSUE THREAD

**Issue by andrewdbate** [moewew/biblatex-trad#32]
The output I am getting when citing a chapter from a book (at least when using trad-alpha) is different to what I was expecting (i.e. it is different to BibTeX alpha).

When citing a book chapter, the biblography says _**part instead of chapter**_.

For example, for the BibTeX entry in `references.bib`
```
@incollection{TestKey,
    author       = {Joe Bloggs},  
    title        = {The Interesting Chapter Title},
    chapter      = {9},
    pages        = {100--207},
    booktitle    = {The Best Book Title},
    editor       = {John Mann and Peter Person},
    publisher    = {Cambridge University Press},
    year         = {1997},
}
```
with the LaTeX document `document.tex` using BibTeX
```
\documentclass{article}
\begin{document}
\bibliographystyle{alpha}
\cite{TestKey}
\bibliography{references}
\end{document}
```
the reference is printed as

![bug-report-1](https://user-images.githubusercontent.com/2998569/35657469-8b461c64-06f4-11e8-920b-7fc5680d9dc4.png)

whereas with the LaTeX document `document2.tex` using BibLaTeX and trad-alpha
```
\documentclass{article}
\usepackage[backend=biber,style=trad-alpha]{biblatex}
\addbibresource{references.bib}
\begin{document}
\cite{TestKey}
\printbibliography
\end{document}
```
this is the (incorrect output) that I am getting:

![bug-report-2](https://user-images.githubusercontent.com/2998569/35657571-0acf7f52-06f5-11e8-995d-d86069588d91.png)

The string "part" should instead be "chapter".

**Comment by moewew** [comment]
Thank you for reporting this.

The issue should be fixed with commit 368a07a. I'm currently looking at a few other things and hope to release a fixed version soon.

**Comment by moewew** [comment]
Version v0.4 with the fix has been sent off to CTAN.

**Comment by andrewdbate** [comment]
Do you know roughly how long it takes to appear on CTAN from experience?

**Comment by moewew** [comment]
Normally things are up on CTAN within a day, but then it takes another day to propagate through to all mirrors. TeX live regularly pulls from CTAN, so you can expect it there in the next two to three days. MikTeX does the updates manually, so it could take a bit longer.

If you need a fix *now* you can simply add
```
\DeclareFieldFormat{chapter}{\bibstring{chapter}~#1}
```
to your preamble. Or get the files from GitHub and place them in the same directory as your `.tex` file (but then don't forget to delete the local files as soon as the update has arrived.)
