### ISSUE TITLE
Dutch and German author names not output as expected

### ISSUE THREAD

**Issue by andrewdbate** [moewew/biblatex-trad#34]
The output from trad-alpha when citing an entry with a Dutch or German author name is different to BibTeX alpha.

The key thing here is names like `de Neville` (with lowercase `d`) or `van Dyke` (with lowercase `v` as is common in the Netherlanders) or `Van Dyke` (with capital `V` as is common in the US).

For example, given `references.bib`
```
@book{deNeville1999,
  author    = {Isabel de Neville},
  title     = {{Handbook of Something Important}},
  publisher = {Science Publishers},
  series    = {Foundations of Interesting Things},
  year      = 1999
}

@book{vanDyke2007,
  author    = {Harry van Dyke and Bob Brown},
  title     = {{Handbook of Something Else}},
  publisher = {Science Publishers},
  series    = {Foundations of Interesting Things},
  year      = 2007
}

@book{DickVanDyke2015,
  author    = {Dick Van Dyke},
  title     = {{Keep Moving}},
  publisher = {Hachette Books},
  year      = 2015
}
```
with the LaTeX document `document.tex` using BibTeX
```latex
\documentclass{article}
\begin{document}
\bibliographystyle{alpha}
\cite{deNeville1999}
\cite{vanDyke2007}
\cite{DickVanDyke2015}
\bibliography{references}
\end{document}
```
the references are printed as

![bug-bibtex](https://user-images.githubusercontent.com/2998569/36343644-c2d93dfe-1406-11e8-858e-529a0cf134a6.png)

whereas with the LaTeX document `document2.tex` using BibLaTeX and trad-alpha
```latex
\documentclass{article}
\usepackage[backend=biber,style=trad-alpha]{biblatex}
\addbibresource{references.bib}
\begin{document}
\cite{deNeville1999}
\cite{vanDyke2007}
\cite{DickVanDyke2015}
\printbibliography
\end{document}
```
this is the (incorrect output) that I am getting:

![bug-biblatex](https://user-images.githubusercontent.com/2998569/36343673-0b66fd18-1407-11e8-8f81-7e655b60e3dc.png)

You can see that the citation labels are different. (I don't know for certain what the "correct" thing to do is, but I believe that BibTeX alpha has got it right.)

Is there a workaround that can be used to get the same behaviour?

**Comment by moewew** [comment]
Thank you for reporting this.

With `useprefix=true` we can get as far as

```latex
\documentclass{article}
\usepackage[backend=biber,style=trad-alpha, useprefix=true]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{deNeville1999,
  author    = {Isabel de Neville},
  title     = {{Handbook of Something Important}},
  publisher = {Science Publishers},
  series    = {Foundations of Interesting Things},
  year      = 1999
}

@book{vanDyke2007,
  author    = {Harry van Dyke and Bob Brown},
  title     = {{Handbook of Something Else}},
  publisher = {Science Publishers},
  series    = {Foundations of Interesting Things},
  year      = 2007
}

@book{DickVanDyke2015,
  author    = {Dick Van Dyke},
  title     = {{Keep Moving}},
  publisher = {Hachette Books},
  year      = 2015
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{deNeville1999}
\cite{vanDyke2007}
\cite{DickVanDyke2015}
\printbibliography
\end{document}
```
![untitled-8](https://user-images.githubusercontent.com/6755835/36343821-1eb667e6-1411-11e8-8624-f22a1ed9c00a.png)

This is not exactly what `alpha` does, but certainly closer than what we have at the moment. I'll check if we can get the 'dN' instead of 'dNev', although personally I prefer the latter.

**Comment by andrewdbate** [comment]
Thank you for the speedy reply! It is a huge help. I also prefer 'dNev' over 'dN' and that is okay since I do not require 100% compatibility.

Is there a reason why `useprefix=true` is not the default behaviour for `trad-alpha`? (I'm not familiar with the design decision rationale for BibLaTeX and `biblatex-trad`.)

**Comment by moewew** [comment]
Good. I have found no good or easy way to obtain 'dN', so I'm quite happy that you don't need 'dNev'. I'll leave it at that.

I have no idea why `useprefix=true` is not the default. It should probably be. I will change that shortly, once I have figured out whether all styles should use it and where to place it.

**Comment by moewew** [comment]
I have pushed https://github.com/moewew/biblatex-trad/commit/fadacd0c7a3135cea4ee9501f77fd1f6cedd361f and sent v0.4a off to CTAN. It will probably land in your favourite distribution in a few days.

**Comment by moewew** [comment]
v0.4a is now available on MikTeX and TeX live. The introductory example gives more desirable output now, I'm closing this for now. If there is anything else, just comment here or open a new issue.
