### ISSUE TITLE
How to compress cites?

### ISSUE THREAD

**Issue by eboigne** [moewew/biblatex-trad#36]
Hello,

Thanks for the contribution, working great for my thesis! I'm looking to use the "compress" bib option, with which [1,2,3,4] becomes [1-4]. I couldn't make it work with biblatex options. I'm using:
```
\usepackage[backend=bibtex,sorting=none,style=trad-abbrv,citestyle=numeric,sortcites=true]{biblatex}
```

In biblatex, it seems that compressing is done by using the compact "-comp" version of the desired style: https://www.overleaf.com/learn/latex/Biblatex_citation_styles, https://tex.stackexchange.com/questions/61524/sort-but-do-not-compress-numeric-citations-in-biblatex. Is there any chance you'd have that option for these native styles? I'm particularly interested in `trad-abbrv-comp`. Thanks in advance!

**Comment by moewew** [comment]
The  `.cbx` files (i.e. the citation styles of this bundle) are just imports of the standard `biblatex` base styles (`numeric` for and [`trad-abbrv`](https://github.com/moewew/biblatex-trad/blob/dev/trad-abbrv.cbx), [`trad-plain`](https://github.com/moewew/biblatex-trad/blob/dev/trad-plain.cbx) and [`trad-unsrt`](https://github.com/moewew/biblatex-trad/blob/dev/trad-unsrt.cbx) and `alphabetic` for [`trad-alpha`](https://github.com/moewew/biblatex-trad/blob/dev/trad-alpha.cbx)), so you don't lose anything if you explicitly select a different `citestyle` (as you did already). Just go with `citestyle=numeric-comp,`.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=bibtex, style=trad-abbrv, citestyle=numeric-comp, sorting=none,]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,worman,geer,nussbaum}

\printbibliography
\end{document}
```
![Lorem [1–4]](https://user-images.githubusercontent.com/6755835/207806892-78cb284d-dda9-40cd-8bd8-fd12481c7cbc.png)

**Comment by eboigne** [comment]
Understood, this works great! Thanks for the quick help.
